# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyVideoGames', '0002_auto_20170429_0956'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Themes',
            new_name='Theme',
        ),
        migrations.AddField(
            model_name='videogame',
            name='themes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MyVideoGames.Theme'),
            preserve_default=False,
        ),
    ]
