# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyVideoGames', '0004_auto_20170430_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MyVideoGames.VideoGame'),
            preserve_default=False,
        ),
    ]
